name: VMT
channels:
  - defaults
dependencies:
  - aom=3.12.1=ha237518_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hfe05a68_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - cyrus-sasl=2.1.28=h5aace77_4
  - dav1d=1.2.1=h80987f9_0
  - eigen=5.0.1=h9e3ec18_0
  - expat=2.7.4=h50f4ffc_0
  - ffmpeg=6.1.1=h5e6af82_5
  - fontconfig=2.15.0=h29935d0_0
  - freetype=2.14.1=h7cdc921_0
  - fribidi=1.0.16=h8859324_0
  - gdk-pixbuf=2.44.4=hf47f480_0
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=h313beb8_1
  - giflib=5.2.2=h80987f9_0
  - glib=2.86.3=h863a760_0
  - glib-tools=2.86.3=hff4a405_0
  - glog=0.5.0=h313beb8_1
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.24.12=hc962c03_1
  - gstreamer=1.24.12=h4a1bc71_1
  - gstreamer-orc=0.4.42=h666e35a_0
  - harfbuzz=10.2.0=he637ebf_1
  - hdf5=1.14.5=hd77251f_2
  - icu=73.1=h313beb8_0
  - jansson=2.14=h80987f9_1
  - jpeg=9f=h2f69dba_0
  - lame=3.100=h5f1bbbb_1
  - lcms2=2.17=h7418793_0
  - leptonica=1.82.0=hdedf53e_3
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250814.1=cxx17_hbea547f_0
  - libarchive=3.8.2=ha845c4f_0
  - libavif=1.3.0=h839b4eb_0
  - libbrotlicommon=1.2.0=hbd7815e_0
  - libbrotlidec=1.2.0=h1e834b2_0
  - libbrotlienc=1.2.0=h5439a07_0
  - libcurl=8.18.0=hd4c70c6_0
  - libcxx=21.1.8=hb4ce287_0
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=15.2.0=h09d7db9_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.86.3=hcacd345_0
  - libiconv=1.18=h92f5915_0
  - libidn2=2.3.8=h9681e36_0
  - libkrb5=1.22.1=ha46c28b_0
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.67.1=h8189af8_0
  - libogg=1.3.5=h1a28f6b_1
  - libopenblas=0.3.31=h7813bb4_0
  - libopenjpeg=2.5.4=haa24f5a_1
  - libopus=1.6.1=hcaaa34f_0
  - libpng=1.6.54=h5c318fc_0
  - libpq=17.6=h5b163ea_1
  - libprotobuf=6.33.0=h6acce77_1
  - librsvg=2.56.3=h38920c8_2
  - libsodium=1.0.20=h897f8a9_0
  - libssh2=1.11.1=h3e2b118_0
  - libtheora=1.2.0=h7de75a5_1
  - libtiff=4.7.1=h367c460_0
  - libunistring=1.3=h1799b2a_0
  - libvorbis=1.3.7=he508a53_1
  - libvpx=1.15.2=h6b4e6e5_0
  - libwebp=1.6.0=h30d73d9_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxcb=1.17.0=h3fc13f7_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.8=hfab7639_0
  - lmdb=0.9.31=h79febb2_0
  - lz4-c=1.9.4=h313beb8_1
  - mysql-common=9.3.0=h2890792_4
  - mysql-libs=9.3.0=h75874b4_4
  - ncurses=6.5=hee39554_0
  - numpy=2.4.2=py314hde9b8b7_0
  - numpy-base=2.4.2=py314hb4b2851_0
  - opencv=4.12.0=py314h830cfcc_1
  - openh264=2.6.0=hc17ed81_1
  - openjpeg=2.5.4=h959fc53_1
  - openldap=2.6.12=he6ca1aa_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py314hca03da5_1
  - pango=1.50.7=hf2328af_2
  - pcre2=10.46=h1dacb4a_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - pthread-stubs=0.3=h1a28f6b_1
  - python=3.14.2=h1858270_101_cp314
  - python_abi=3.14=2_cp314
  - qtbase=6.9.2=h297ff01_5
  - readline=8.3=h0b18652_0
  - setuptools=80.10.2=py314hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tesseract=5.2.0=h9e66425_3
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py314hca03da5_0
  - xorg-libxau=1.0.12=h3fc13f7_0
  - xorg-libxdmcp=1.1.5=h3fc13f7_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/VMT
